export default {
  bufferLength: 37,
  tickDurationOverC: 5.949858802153492e-2,
  loop: false,
  stepWise: false,
  particleCount: 1,
  particleType: 'ELECTRON',
  bunchShape: 'ROW',
  particleSeparation: 0.01,
  emitterDirection: [0, 0.1, 1],
  gamma: 200,
  particleInteraction: false,
  electricFieldStrength: 0,
  dipole_strength: 1,
  dipole_minZ: -100,
  dipole_maxZ: 100,
  quadrupole_1_strength: 0,
  quadrupole_1_rotated: false,
  quadrupole_1_minZ: 0,
  quadrupole_1_maxZ: 0,
  quadrupole_2_strength: 0,
  quadrupole_2_rotated: true,
  quadrupole_2_minZ: 0,
  quadrupole_2_maxZ: 0
}
