input: files/screenshots
output: ./../../../screenshots/

pipeline:
  - pipe: resize
    options:
      breakpoints:
        # - name: sm
        #   resizeOptions:
        #     width: 480
        # - name: md
        #   resizeOptions:
        # width: 720
        - name: lg
          resizeOptions:
            width: 1920
        # - name: xl
        #       resizeOptions:
        #         width: 3840
        # # save: '[name]-[breakpoint][ext]'
    then:
      - pipe: convert
        options:
          format: jpeg
        save: '[name][ext]'
