input: files/orig
output: dist/

pipeline:
  - pipe: convert
    options:
      format: jpg
    save: '[source.name].jpg'
  - pipe: convert
    options:
      format: webp
    save: '[source.name].webp'
